mod content_process;
mod desktop;
mod desktop_attachment;
mod dock;
mod main_ui_process;
pub mod main_window;
mod menu;
mod monitor;
mod msg_id;
mod occlusion;
mod resource_ids;
mod tray_icon;
pub mod wallpaper_manager;
mod watcher;
