mod content_process;
mod desktop;
mod desktop_attachment;
mod dock;
mod main_ui_process;
pub mod main_window;
mod menu;
mod monitor;
mod msg_id;
mod occlusion;
pub(crate) mod player;
mod resource_ids;
mod tray_icon;
mod video_host;
pub mod wallpaper_manager;
mod watcher;
pub(crate) mod webview;
mod wide_string;
