[package]
name = "x-desk"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["crates/*", "sub-apps/x-desk-main-ui/src-tauri"]

[workspace.dependencies]
anyhow = "1.0.104"
serde = { version = "1.0.229", features = ["derive"] }
toml = "0.8.23"
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_Gdi",
    "Win32_Media_MediaFoundation",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Com",
    "Win32_System_IO",
    "Win32_System_Pipes",
    "Win32_System_LibraryLoader",
    "Win32_System_RemoteDesktop",
    "Win32_System_Threading",
    "Win32_UI_Shell",
    "Win32_UI_HiDpi",
    "Win32_UI_Accessibility",
    "Win32_UI_WindowsAndMessaging",
] }

[[bin]]
name = "x-desk-player"
path = "src/processes/x-desk-player.rs"

[[bin]]
name = "x-desk-webview"
path = "src/processes/x-desk-webview.rs"

[dependencies]
anyhow = { workspace = true }
config = { path = "crates/config" }
log = "0.4.33"
regex = "1.12.2"
single-instance = { path = "crates/single-instance" }
windows = { workspace = true }
windows-core = "0.62.2"
windows-implement = "0.60.2"
webview2-com = "0.39.1"


[build-dependencies]
embed-resource = "2.5"
